export class cache_talent{
  //General Info
  _NAME;
  _AGE;
  _CITIZENSHIP;
  _RELIGION;
  _CIVIL_STATUS;
  _GENDER;
  _COUNTRY;
  _LOCATION;
  _TALENT_SUPPLIER;
  _TALENT_HANDLER;
  _INTEREST;
  _SKILL_TALENT;

  //Characteristics
  _HEIGHT;
  _WEIGHT;
  _BUILT;
  _EYE_COLOR;
  _HAIR_COLOR;
  _SKINTONE;
  _VITAL_STATISTICS;
  _SPECIFIC_CHAR;
  _TALENT_TYPE;

  //For select options
  _CITIZENSHIP_POP=false;
  _RELIGION_POP=false;
  _CIVIL_STATUS_POP=false;
  _GENDER_POP=false;
  _COUNTRY_POP=false;
  _LOCATION_POP=false;
  _INTEREST_POP=false;
  _SKILL_TALENT_POP=false;


  //General Info OR/Like any of/And
  _NAME_AND_OR=2;
  _AGE_AND_OR=0;
  _CITIZENSHIP_AND_OR=2;
  _RELIGION_AND_OR=2;
  _CIVIL_STATUS_AND_OR=2;
  _GENDER_AND_OR=2;
  _COUNTRY_AND_OR=2;
  _LOCATION_AND_OR=2;
  _TALENT_SUPPLIER_AND_OR=2;
  _TALENT_HANDLER_AND_OR=2;
  _INTEREST_AND_OR=2;
  _SKILL_TALENT_AND_OR=2;

  //Characteristics Info OR/Like any of/And
  _HEIGHT_AND_OR=2;
  _WEIGHT_AND_OR=2;
  _BUILT_AND_OR=2;
  _EYE_COLOR_AND_OR=2;
  _HAIR_COLOR_AND_OR=2;
  _SKINTONE_AND_OR=2;
  _VITAL_STATISTICS_AND_OR=2;
  _SPECIFIC_CHAR_AND_OR=2;
  _TALENT_TYPE_AND_OR=2;

  //General Info radio button
  _NAME_RADIO_BUTTON=1;
  _AGE_RADIO_BUTTON=1;
  _CITIZENSHIP_RADIO_BUTTON=1;
  _RELIGION_RADIO_BUTTON=1;
  _CIVIL_STATUS_RADIO_BUTTON=1;
  _GENDER_RADIO_BUTTON=1;
  _COUNTRY_RADIO_BUTTON=1;
  _LOCATION_RADIO_BUTTON=1;
  _TALENT_SUPPLIER_RADIO_BUTTON=1;
  _TALENT_HANDLER_RADIO_BUTTON=1;
  _INTEREST_RADIO_BUTTON=1;
  _SKILL_TALENT_RADIO_BUTTON=1;

  //Characteristics Info radio button
  _HEIGHT_RADIO_BUTTON=1;
  _WEIGHT_RADIO_BUTTON=1;
  _BUILT_RADIO_BUTTON=1;
  _EYE_COLOR_RADIO_BUTTON=1;
  _HAIR_COLOR_RADIO_BUTTON=1;
  _SKINTONE_RADIO_BUTTON=1;
  _VITAL_STATISTICS_RADIO_BUTTON=1;
  _SPECIFIC_CHAR_RADIO_BUTTON=1;
  _TALENT_TYPE_RADIO_BUTTON=1;



  _HAS_FIRED = false;

  //Array
  _CITIZENSHIP_ARR = [];
  _RELIGION_ARR = [];
  _CIVIL_STATUS_ARR = [];
  _GENDER_ARR = [{ref: 'M', desc: 'MALE'}, {ref:'F', desc:'FEMALE'}];
  _COUNTRY_ARR = [];
  _LOCATION_ARR = [];
  _INTEREST_ARR = [];
  _SKILL_TALENT_ARR = [];


  QUERY_VAL = [];

  PARTTIME_MSTR;
  CITIZESHIP_MSTR;
  ALIAS_MSTR;
  INDIVIDUAL_MSTR;
  GROUP_MSTR;
  COUNTRY_MSTR;
  INTEREST_MSTR;
  SKILL_TALENT_MSTR;
  CHARACTERISTICS_MSTR;
  ALL_MSTR=[];
}
